### ISSUE TITLE
ImportError: cannot import name 'uname' from 'os' 

### ISSUE THREAD

**Issue by junky123** [devblack/OlsoAttack#2]
Traceback (most recent call last):
  File "Olso.py", line 2, in <module>
    from os import uname
ImportError: cannot import name 'uname' from 'os' 

I am in windows rdp
and this issue occured while executing Olso.py

**Comment by devblack** [comment]
Fixed in the new version thank for report.

**Comment by junky123** [comment]
![image](https://user-images.githubusercontent.com/54109630/93325211-ce501d00-f7cb-11ea-9ce7-c50e8a3264cf.png)

**Comment by devblack** [comment]
That error is from the socks lib creator, you can fix it replacing in the '**### C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiosocks\**' dir, replace connector.py with the Olso Attack connector.py

**Comment by junky123** [comment]
Thank You So much bro
Working
